import requests
from concurrent.futures import ThreadPoolExecutor, as_completed

# Paste your list of URLs here
urls = [
  "https://www.baxleynewsbanner.com",
  "https://www.atkinsoncitizennews.com",
  "https://www.almatimes.com",
  "https://bakercountypress.com/",
  "https://baldwintimes.com/",
  "https://www.thebankspost.com",
  "https://www.mainstreetnews.com/barrow/",
  "https://www.bartowcountyga.gov/news",
  "https://www.fitzgeraldherald.com",
  "https://www.berriengazette.com",
  "https://www.maconbibb.us/news/",
  "https://www.cochranjournal.com",
  "https://www.thebrunswicknews.com",
  "https://www.valdostadailytimes.com",
  "https://www.bryancountyga.org/news",
  "https://www.bullochcounty.net/news-events",
  "https://www.northwestgeorgianews.com/calhoun_times/",
  "https://www.camdencountyga.gov/156/News",
  "https://www.metteradvertiser.com",
  "https://www.carrollcountygacom/important-news",
  "https://www.northwestgeorgianews.com/catoosa_walker_news/",
  "https://www.charltoncountycourier.com",
  "https://www.chathamcountyga.gov/News",
  "https://www.wrbl.com/news/local-news/chattahoochee-county/",
  "https://www.northwestgeorgianews.com",
  "https://www.cherokeega.com/News",
  "https://www.accgov.com/156/News",
  "https://www.claytoncountyga.gov/government/communications/newsletters",
  "https://www.theclinchcountynews.com/",
  "https://www.cobbcounty.org/communications/news",
  "https://www.columbiacountyga.gov/county-news",
  "https://www.adelnews.com",
  "https://www.coweta.ga.us/news",
  "https://www.crawfordcountyga.org/news/",
  "https://www.dadenews.com",
  "https://www.dawsoncounty.org/news",
  "https://www.dekalbcountyga.gov/news",
  "https://www.couriernews.com",
  "https://www.viennawire.com",
  
  "https://www.celebratedouglascounty.com/news",
  "https://www.earlycountynews.com",
  "https://www.effinghamcounty.org/156/News",
  "https://www.elberton.com",
  "https://www.theswainsboroblade.com",
  "https://www.claxtonenterprise.com",
  "https://www.fannin.news",
  "https://fayettecountyga.gov/news",
  "https://www.floydcountyga.gov/news",
  "https://www.forsythco.com/News",
  "https://www.mtvernonnews.com",
  "https://www.glascockcountyga.com/news",
  "https://www.glynncounty.org/156/News",
  "https://gordoncounty.org/news/",
  "https://www.greenecountyheraldonline.com/",
  "https://www.gwinnettcounty.com/news",
  "https://nowhabersham.com/",
  "https://www.hallcounty.org/156/News",
  "https://www.harriscountyga.com",
  "https://www.times-georgian.com",
  "https://www.henrycountyga.gov/156/News",
  "https://www.houstoncountyga.org/news",
  "https://www.ocillaleader.com",
  "https://www.jacksoncountygov.com/149/News",
  "https://www.jeffdavistimes.com",
  "https://www.millencitizen.com",
  "https://www.johnsonco.org/news",
  "https://www.jcnewsonline.com",
  "https://www.laniercountynewsonline.com/",
  "https://www.courier-herald.com",
  "https://www.leesentinel.com",
  "https://www.libertycountyga.com/156/News",
  "https://www.thejournalmessenger.com/",
  "https://www.lowndescounty.com/156/News",
  "https://www.thedahloneganugget.com",
  "https://www.maconcountynews.com",
  "https://www.madisonjournaltoday.com",
  "https://www.mcduffieprogress.com/",
  "https://www.coastalcourier.com",
  "https://www.manchestermercury.com",
  "https://www.millercountyliberal.com/",
  "https://www.millercountyliberal.com",
  "https://www.mymcr.net/news/",
  "https://www.morgancountycitizen.com",
  "https://www.columbusga.gov/News",
  "https://www.co.newton.ga.us/156/News",
  "https://www.oconeecounty.com/156/News",
  "https://www.theoglethorpeecho.com/local-news",
  "https://www.paulding.gov/156/News",
  "https://www.peachcountynews.com",
  "https://pickensprogress.com/",
  "https://www.blackshearnews.com",
  "https://pikecountygeorgia.com/",
  "https://www.polkcountyenterprise.com",
  "https://www.hawkinsvilleprogress.com",
  "https://www.eatontonmessenger.com",
  "https://www.thequitmanfreepress.com/",
  "https://www.theclaytontribune.com",
  "https://www.therandolphleader.com/news/",
  "https://www.augustaga.gov/156/News-Center",
  "https://www.rockdalecountyga.gov/156/News",
  "https://www.thesylvaniatimes.com/",
  "https://www.donalsonvillenews.com",
  "https://www.breckenridgetexan.com",
  "https://talbottonnewera.com/",
  "https://www.tattnalljournal.com",
  "https://www.taylorcountypress.com",
  "https://www.macontelegraph.com",
  "https://www.timesenterprise.com",
  "https://www.tiftongazette.com",
  "https://www.southeastsun.com",
  "https://www.northgeorgianews.com",
  "https://www.troupcountyga.gov/News",
  "https://www.ashburnwire.com",
  "https://www.northgeorgianews.com",
  "https://www.thomastontimes.com",
  "https://www.walkercountygov.com/news",
  "https://www.waltoncountyga.gov/156/News",
  "https://www.warecountygazette.com",
  "https://www.wjbf.com/news/warren-county/",
  "https://www.thesandersvillereport.com",
  "https://www.thepress-sentinel.com",
  "https://www.whitecountynews.net",
  "https://www.whitfieldcountyga.com/news",
  "https://www.wilcoxsun.com",
  "https://www.wilkinsoncounty.net/category/news/",
  "https://www.sylvesterlocal.com",
  "https://www.co.anderson.tx.us/news",
  "https://www.andrewscountynews.com",
  "https://www.angelinacounty.net/county-news/",
  "https://www.aransascountytx.gov/news",
  "https://www.archercountynews.com",
  "https://austincountynewsonline.com/",
  "https://www.muleshoejournal.com",
  "https://www.banderabulletin.com/",
  "https://www.co.bastrop.tx.us/news",
  "https://www.seymournews.com",
  "https://www.bellcountytx.com/news",
  "https://www.bexar.org/CivicAlerts.aspx",
  "https://www.hillcountrypassport.com/blanco/",
  "https://www.co.borden.tx.us/",
  "https://www.bosquecountypublishing.com",
  "https://www.bowiecountynow.com/",
  "https://www.brazoriacountytx.gov/news",
  "https://www.brazoscountytx.gov/156/News",
  "https://www.valdostadailytimes.com",
  "https://www.burlesoncountyledger.com",
  "https://www.burnetbulletin.com/",
  "http://www.mycaldwellcounty.com/news",
  "https://www.callahancountynews.com",
  "https://www.cameroncountytx.gov/news",
  "https://www.pittsburgnews.com",
  "https://www.casscountynow.com/",
  "https://www.castrocountynews.com",
  "https://www.thecherokeean.com/",
  "https://www.childressindex.com",
  "https://www.colemantoday.com/",
  "https://www.collincountytx.gov/news",
  "https://www.coloradocountycitizen.com/",
  "https://www.co.comal.tx.us/News.htm",
  "https://www.thecomanchechief.com/news/county_news/",
  "https://www.cranenews.com",
  "https://crockettcountytimes.com/",
  "https://www.crosbycountynews.com",
  "https://www.dallamcountynews.com",
  "https://www.dallascounty.org/news",
  "https://www.lamesacourier.com",
  "https://www.deltacountyindependent.com/",
  "https://www.dentoncounty.gov/156/News",
  "https://www.cuerorecord.com",
  "https://www.carrizoenterprise.com",
  "https://www.clarendonlive.com",
  "https://www.duvalcountytimes.com",
  "https://www.co.ellis.tx.us/156/News",
  "https://www.epcounty.com/news.htm",
  "https://www.marlinnews.com",
  "https://www.fannin.news",
  "https://www.floydadanews.com",
  "https://www.fortbendcountytx.gov/news",
  "https://www.mtvernonnews.com",
  "https://freestonecountytimesonline.com/",
  "https://www.friotime.com",
  "https://www.galvestontx.gov/156/Notify-Me",
  "https://www.postdispatch.com",
  "https://www.fredericksburgstandard.com",
  "https://www.gonzalesinquirer.com",
  "https://www.co.grayson.tx.us/news",
  "https://www.navasotanews.com",
  "https://www.co.guadalupe.tx.us/news",
  "https://www.hamiltonherald-news.com",
  "https://www.hansfordnews.com",
  "https://www.hardincoindependent.com/category/news/",
  "https://www.harriscountytx.gov/News",
  "https://www.haskellstar.com",
  "https://www.hayscountytx.gov/news"
]

def is_scrapable(url):
    try:
        resp = requests.get(url, timeout=10, headers={
            "User-Agent": "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
        })
        # Consider scrapable if status code is 200 and content-type is HTML
        if resp.status_code == 200 and 'text/html' in resp.headers.get('Content-Type', ''):
            return url
    except Exception as e:
        print(f"Failed: {url} ({e})")
    return None

def main():
    scrapable = []
    with ThreadPoolExecutor(max_workers=10) as executor:
        futures = {executor.submit(is_scrapable, url): url for url in urls}
        for future in as_completed(futures):
            result = future.result()
            if result:
                scrapable.append(result)
                print(f"Scrapable: {result}")
    # Save to file
    with open("scrapable_urls.txt", "w") as f:
        for url in scrapable:
            f.write(url + "\n")
    print(f"Found {len(scrapable)} scrapable URLs. See scrapable_urls.txt.")

if __name__ == "__main__":
    main()