import json
import random
import asyncio
from playwright.async_api import async_playwright

# List of search pages for fire-related news
NEWS_SITES = [
#     "https://www.cnn.com/search?q=fire",
#     "https://www.foxnews.com/search-results/search?q=fire",
#     "https://www.nbcnews.com/search/?q=fire",
#     "https://www.cbsnews.com/search/?q=fire",
#     "https://www.abcnews.go.com/search?q=fire",
#     "https://www.nytimes.com/search?query=fire",
#     "https://www.latimes.com/search?q=fire",
#     "https://www.chicagotribune.com/search/?q=fire",
#     "https://www.boston.com/search/?q=fire",
#     "https://www.dallasnews.com/search/?q=fire",
#     "https://local12.com/search?find=fire",
#     "https://www.wtnh.com/?submit&s=fire&orderby=modified",
#    "https://www.wtnh.com/page/2/?submit&s=fire&orderby=modified",
#    "https://www.wtnh.com/page/3/?submit&s=fire&orderby=modified",
#     "https://www.cbs17.com/?submit=&s=fire&orderby=modified",
#     "https://www.cbs17.com/page/2/?submit&s=fire&orderby=modified",
#     "https://www.cbs17.com/page/3/?submit&s=fire&orderby=modified",
#     "https://www.wbir.com/search?q=fire",
#     "https://www.wcvb.com/search?q=fire",
#     "https://www.knoxnews.com/search/?q=fire",
#     "https://westchester.news12.com/search?q=fire",
#     "https://www.wfmz.com/search/?q=fire",
#     "https://news4sanantonio.com/search?find=fire",
#     "https://www.wivb.com/?submit=&s=fire",
#     "https://www.nbcconnecticut.com/?s=fire",
#     "https://www.al.com/search/?q=fire",
#     "https://cullmantimes.com/",
#         "https://www.westvalleyview.com/search/?q=fire",
#     "https://www.chandlernews.com/search/?q=fire",
#     "https://www.glendalestar.com/search/?q=fire",
#     "https://www.yourvalley.net/search/?q=fire",
#     "https://www.gilbertsunnews.com/search/?q=fire",
#     "https://flagscanner.com/?s=fire",
#     "https://www.yumanewsnow.com/search/?q=fire",
#     "https://www.havasunews.com/search/?q=fire",
#     "https://www.tucsonsentinel.com/search/?q=fire",
#     "https://www.tucsonlocalmedia.com/search/?q=fire",
#     "https://www.gvnews.com/search/?q=fire",
#         "https://www.kodiakdailymirror.com/search/?q=fire",
#     "https://sitkasentinel.com/search/?q=fire",
#     "https://www.latimes.com/search?q=fire",
#     "https://www.dailynews.com/search/?q=fire",
#     "https://www.laweekly.com/search/?q=fire",
#     "https://www.ladowntownnews.com/search/?q=fire",
#     "https://www.glendalenewspress.com/search/?q=fire",
#     "https://www.burbankleader.com/search/?q=fire",
#     "https://www.pasadenastarnews.com/search/?q=fire",
#     "https://www.dailybreeze.com/?s=fire&orderby=date&order=desc",
#     "https://malibutimes.com/?s=fire",
#     "https://smdp.com/?s=fire",
#     "https://www.fresnostatenews.com//?s=fire",
#     "https://www.selmaenterprise.com",
#     "https://kerwestnewspapers.com",
#     "https://www.sfchronicle.com",
#     "https://www.sfexaminer.com",
#     "https://www.sanfranciscochinatown.com",
#     "https://sfbayview.com",
#     "https://www.sacramentopress.com",
#     "https://elkgrovetribune.com",
#     "https://goldcountrymedia.com",
#     "https://citrusheightssentinel.com",
#     "https://www.davisenterprise.com",
#     "https://www.natomasbuzz.com",
#     "https://www.carmichaeltimes.com",
#     "https://sacramento.newsreview.com",
#     "https://www.mercurynews.com",
#     "https://sanjosespotlight.com",
#     "https://local.newsbreak.com",
#     "https://www.bakersfield.com",
#     "https://www.anaheim.net",
#     "https://www.independent.com",
#     "https://www.santamariasun.com",
#     "https://goletavoice.com",
#     "https://santamariatimes.com",
#     "https://lompocrecord.com",
#     "https://syvnews.com",
#     "https://www.montecitojournal.net",
#     "https://dailynexus.com",
#     "https://www.longbeachlocalnews.com",
#     "https://www.sandiegouniontribune.com",
#     "https://timesofsandiego.com",
#     "https://www.chulavistatoday.com",
#     "https://www.times-advocate.com",
#     "https://thecoastnews.com",
#     "https://www.thevistapress.com",
#     "https://www.sanmarcosrecord.com",
#     "https://www.imperialbeachnewsca.com",
#     "https://signalscv.com",
#     "https://www.dailycommerce.news",
#     "https://www.thecamarilloacorn.com",
#     "https://www.newsbreak.com",
#     "https://vidanewspaper.com",
#     "https://www.vcstar.com",
#     "https://www.toacorn.com",
#     "https://www.simivalleyacorn.com",
#     "https://www.fillmoregazette.com",
#     "https://www.mpacorn.com",
#     "https://www.ojaivalleynews.com",
#     "https://santapaulatimes.com",
#     "https://www.desertsun.com",
#     "https://orangecountytribune.com",
#     "https://www.aspendailynews.com/",
#     "https://www.dailycamera.com/",
#     "https://www.canoncitydailyrecord.com/",
#     "https://gazette.com/",
#     "https://www.craigdailypress.com/",
#     "https://www.durangoherald.com/",
#     "https://www.coloradoan.com/",
#     "https://www.fortmorgantimes.com/",
#     "https://www.summitdaily.com/",
#     "https://www.gjsentinel.com/",
#     "https://www.greeleytribune.com/",
#     "https://www.lajuntatribunedemocrat.com/",
#     "https://www.timescall.com/",
#     "https://www.reporterherald.com/",
#     "https://www.montrosepress.com/",
#     "https://www.chieftain.com/",
#     "https://www.vaildaily.com/",
#     "https://www.ctpost.com/",
#     "https://www.bristolpress.com/",
#     "https://www.greenwichtime.com/",
#     "https://www.newstimes.com/",
#     "https://www.courant.com/",
#     "https://www.ctinsider.com",
#     "https://www.middletownpress.com/",
#     "https://www.nhregister.com/",
#     "https://theday.com/",
#     "https://www.thehour.com/",
#     "https://www.norwichbulletin.com/",
#     "https://www.stamfordadvocate.com/",
#     "https://www.rep-am.com/",
#     "https://www.thechronicle.com/",
#     "https://baytobaynews.com/",
#     "https://www.delawareonline.com/",
#     "https://washingtoncitypaper.com",
#     "https://www.washingtonpost.com",
#     "https://www.washingtonian.com",
#     "https://www.heraldtribune.com",
#     "https://www.snntv.com",
#     "https://www.mysuncoast.com",
#     "https://thebradentontimes.com",
#     "https://www.bradenton.com",
#     "https://cityofbradenton.com",
#     "https://www.tampabay.com",
#     "https://www.wtsp.com",
#     "https://www.tampabeacon.com",
#     "https://fortmyers.floridaweekly.com",
#     "https://www.miaminewtimes.com",
#     "https://www.miamiherald.com",
#     "https://www.miamitodaynews.com",
#     "https://www.orlandoweekly.com",
#     "https://www.cityofcocoabeach.com",
#     "https://www.ocala.com",
#     "https://www.ocalagazette.com",
#     "https://www.jaxdailyrecord.com",
#     "https://www.yoursun.com",
#     "https://veronews.com",
#     "https://www.tcpalm.com",
#     "https://www.cityofpsl.com",
#     "https://ourtallahassee.com",
#     "https://www.news-press.com",
#     "https://www.hollywoodreporter.com",
#     "https://www.gainesville.com",
#     "https://palmbaylive.com",
#     "https://www.palmbeachpost.com",
#     "https://lakelandtimes.com",
#     "https://communitynewspapers.com",
#     "https://thegavoice.com",
#     "https://www.mdjonline.com",
#     "https://patch.com",
#     "https://decaturish.com",
#     "https://www.augustachronicle.com",
#     "https://maconhomepress.com",
#     "https://www.savannahtribune.com",
#     "https://www.onlineathens.com",
#     "https://www.rdrnews.com",
#     "https://www.hawaiitribune-herald.com/",
#     "https://www.staradvertiser.com/",
#     "https://www.westhawaiitoday.com/",
#     "https://www.thegardenisland.com/",
#     "https://www.mauinews.com/",
#     "https://cdapress.com/",
#     "https://www.postregister.com/",
#     "https://www.lmtribune.com/",
#     "https://www.idahopress.com/",
#     "https://www.idahostatejournal.com/",
#     "https://shoshonenewspress.com/",
#     "https://magicvalley.com",
#     "https://www.news-gazette.com",
#     "https://capitolnewsillinois.com",
#     "https://www.chicagotribune.com",
#     "https://www.thewoodstockindependent.com",
#     "https://www.dailyherald.com",
#     "https://www.positivelynaperville.com",
#     "https://www.vevaynewspapers.com",
#     "https://www.madisoncourier.com",
#     "https://www.indystar.com",
#     "https://www.ibj.com",
#     "https://apnews.com",
#     "https://www.tristatehomepage.com",
#     "https://www.courierpress.com",
#     "https://www.greaterfortwayneinc.com",
#     "https://bloomingtonian.com",
#     "https://ground.news",
#     "https://www.kokomotribune.com",
#     "https://www.tribstar.com",
#     "https://andersonian.com",
#     "https://www.amestrib.com/",
#     "https://www.swiowanewssource.com/",
#     "https://www.mississippivalleypublishing.com/the_hawk_eye/",
#     "https://carrollspaper.com/",
#     "https://www.thegazette.com/",
#     "https://www.ottumwacourier.com/",
#     "https://www.charlescitypress.com/",
#     "https://www.chronicletimes.com/",
#     "https://www.clintonherald.com/",
#     "https://spectrumnews1.com",
#     "https://www.courier-journal.com",
#     "https://www.pmg-ky1.com",
#     "https://www.wave3.com",
#     "https://bgdailynews.com",
#     "https://www.richmondregister.com",
#     "https://linknky.com",
#     "https://www.dailyindependent.com/",
#     "https://bgdailynews.com/",
#     "https://www.thetimestribune.com/",
#     "https://www.amnews.com/",
#     "https://www.thenewsenterprise.com/",
#     "https://www.state-journal.com/",
#     "https://www.harlanenterprise.net/",
#     "https://www.thegleaner.com/",
#     "https://www.kentuckynewera.com/",
#     "https://www.middlesboronews.com/",
#     "https://www.the-messenger.com/",
#     "https://www.theadvocate.com",
#     "https://www.brproud.com",
#     "https://theneworleanstribune.com",
#     "https://www.gretnaguide.com",
#     "https://www.thestbernardvoice.com",
#     "https://covingtonweekly.com",
#     "https://www.hammondstar.com",
#     "https://www.plaqueminesgazette.com",
#     "https://www.kenner.la.us",
#     "https://thedailyiberian.com",
#     "https://www.centralmaine.com/",
#     "https://www.bangordailynews.com/",
#     "https://www.pressherald.com/times-record/",
#     "https://www.sunjournal.com/",
#     "https://www.baltimoresun.com",
#     "https://baltimoretimes-online.com",
#     "https://www.thebaltimorebanner.com",
#     "https://gaithersburgpost.town.news",
#     "https://www.marylandmatters.org",
#     "https://www.middletownpress.com/",
#     "https://www.thecitizen.com/",
#     "https://www.delmarvanow.com/",
#     "https://www.dailypress.com",
#     "https://www.dailypress.com/",
#     "https://www.fairfaxtimes.com",
#     "https://www.clarionledger.com",
#     "https://www.magnoliareporter.com",
#     "https://www.nwahomepage.com",
#     "https://www.nwnews.com",
#     "https://www.pennlive.com",
#     "https://www.thedailyreview.com",
#     "https://www.delcotimes.com",
#     "https://www.spotlightpa.org",
#     "https://www.nj.com",
#     "https://www.newjerseyherald.com",
#     "https://www.pressofatlanticcity.com",
#        "https://winknews.com/",
#     "https://www.wric.com/",
#     "https://www.us977.com/",
#     "https://www.wdtn.com/",
#     "https://cbs12.com/",
#     "https://patch.com/",
#     "https://www.wbrc.com/",
#     "https://www.mississippivalleypublishing.com/",
#     "https://www.wfmz.com/",
#     "https://signalakron.org/",
#     "https://jgpr.net/",
#     "https://katu.com/",
#     "https://abc7ny.com/",
#     "https://abc6onyourside.com/",
#     "https://www.wtkr.com/",
#     "https://www.clickorlando.com/",
#     "https://www.9news.com/",
#     "https://www.wane.com/",
#     "https://www.yahoo.com/news/",
#     "https://www.wave3.com/",
#     "https://www.tribstar.com/",
#     "https://www.dailyherald.com/",
#     "https://gazette.com/",
#     "https://syvnews.com/",
#     "https://lompocrecord.com/",
#     "https://www.12onyourside.com/",
#     "https://local12.com/",
#     "https://www.live5news.com/",
#     "https://www.fox5atlanta.com/",
#     "https://www.wgem.com/",
#     "https://www.fox35orlando.com/",
#     "https://www.wpri.com/",
#     "https://fox59.com/",
#     "https://www.whas11.com/",
#     "https://www.wlky.com/",
#     "https://www.theolympian.com/",
#     "https://www.wtnh.com/",
#     "https://www.cbsnews.com/",
#     "https://www.wkrn.com/",
#     "https://cnycentral.com/",
#     "https://www.dcnewsnow.com/",
#     "https://fox17.com/",
#     "https://www.nbc4i.com/",
#     "https://www.lubbockonline.com/",
#     "https://www.13wmaz.com/",
#     "https://www.valleynewslive.com/",
#     "https://ktla.com/",
#     "https://www.abc10.com/",
#     "https://www.wtva.com/",
#     "https://abc7chicago.com/",
#     "https://www.news4jax.com/",
#     "https://www.yahoo.com/",
#     "https://www.kiiitv.com/",
#     "https://www.wfmynews2.com/",
#     "https://smokeybarn.com/",
#     "https://www.khou.com/",
#     "https://www.wapt.com/",
#     "https://brooklyn.news12.com/",
#     "https://www.fox5vegas.com/",
#     "https://news3lv.com/",
#     "https://thegeorgiasun.com/",
#     "https://www.expressnews.com/",
#     "https://wbontv.com/",
#     "https://www.pahomepage.com/",
#     "https://kfor.com/",
#     "https://abc7amarillo.com/",
#     "https://www.kltv.com/",
#     "https://abc6onyourside.com/th",
#     "https://www.firstalert4.com/",
#     "https://www.silive.com/",
#     "https://www.star-telegram.com/",
#     "https://www.whec.com/",
#     "https://www.wsoctv.com/",
#     "https://www.11alive.com/",
#     "https://www.wbir.com/",
#     "https://mendofever.com/",
#     "https://fox11online.com/",
#     "https://www.wfaa.com/",
#     "https://www.wavy.com/",
#     "https://www.courier-journal.com/",
#     "https://www.koco.com/",
#     "https://idahonews.com/",
#     "http://northernnewsnow.com/",
#     "https://www.12newsnow.com/",
#     "https://www.kron4.com/",
#     "https://www.fox4news.com/",
#     "https://www.wsfa.com/",
#     "https://krdo.com/",
#     "https://www.azfamily.com/",
#     "https://www.wbay.com/",
#     "https://www.ksn.com/",
#     "https://www.wnct.com/",
#     "https://www.dailypress.com/",
#     "https://www.klkntv.com/",
#     "https://www.wcax.com/",
#     "https://www.newschannel10.com/",
#     "https://www.wkyt.com/",
#     "https://tucson.com/",
#     "https://www.wmtw.com/",
    "https://www.baxleynewsbanner.com", "https://www.atkinsoncitizennews.com", "https://www.almatimes.com", "https://bakercountypress.com/", "https://baldwintimes.com/", "https://www.thebankspost.com", "https://www.mainstreetnews.com/barrow/", "https://www.bartowcountyga.gov/news", "https://www.fitzgeraldherald.com", "https://www.berriengazette.com", "https://www.maconbibb.us/news/", "https://www.cochranjournal.com", "https://www.thebrunswicknews.com", "https://www.valdostadailytimes.com", "https://www.bryancountyga.org/news", "https://www.bullochcounty.net/news-events", "https://www.northwestgeorgianews.com/calhoun_times/", "https://www.camdencountyga.gov/156/News", "https://www.metteradvertiser.com", "https://www.carrollcountygacom/important-news", "https://www.northwestgeorgianews.com/catoosa_walker_news/", "https://www.charltoncountycourier.com", "https://www.chathamcountyga.gov/News", "https://www.wrbl.com/news/local-news/chattahoochee-county/", "https://www.northwestgeorgianews.com", "https://www.cherokeega.com/News", "https://www.accgov.com/156/News", "https://www.claytoncountyga.gov/government/communications/newsletters", "https://www.theclinchcountynews.com/", "https://www.cobbcounty.org/communications/news", "https://www.columbiacountyga.gov/county-news", "https://www.adelnews.com", "https://www.coweta.ga.us/news", "https://www.crawfordcountyga.org/news/", "https://www.dadenews.com", "https://www.dawsoncounty.org/news", "https://www.dekalbcountyga.gov/news", "https://www.couriernews.com", "https://www.viennawire.com", "https://www.dougherty.ga.us/news", "https://www.celebratedouglascounty.com/news", "https://www.earlycountynews.com", "https://www.effinghamcounty.org/156/News", "https://www.elberton.com", "https://www.theswainsboroblade.com", "https://www.claxtonenterprise.com", "https://www.fannin.news", "https://fayettecountyga.gov/news", "https://www.floydcountyga.gov/news", "https://www.forsythco.com/News", "https://www.mtvernonnews.com", "https://www.fultoncountyga.gov/news", "https://www.glascockcountyga.com/news", "https://www.glynncounty.org/156/News", "https://gordoncounty.org/news/", "https://www.greenecountyheraldonline.com/", "https://www.gwinnettcounty.com/news", "https://nowhabersham.com/", "https://www.hallcounty.org/156/News", "https://www.harriscountyga.com", "https://www.times-georgian.com", "https://www.henrycountyga.gov/156/News", "https://www.houstoncountyga.org/news", "https://www.ocillaleader.com", "https://www.jacksoncountygov.com/149/News", "https://www.jeffdavistimes.com", "https://www.millencitizen.com", "https://www.johnsonco.org/news", "https://www.jcnewsonline.com", "https://www.laniercountynewsonline.com/", "https://www.courier-herald.com", "https://www.leesentinel.com", "https://www.libertycountyga.com/156/News", "https://www.thejournalmessenger.com/", "https://www.lowndescounty.com/156/News", "https://www.thedahloneganugget.com", "https://www.maconcountynews.com", "https://www.madisonjournaltoday.com", "https://www.mcduffieprogress.com/", "https://www.coastalcourier.com", "https://www.manchestermercury.com", "https://www.millercountyliberal.com/", "https://www.millercountyliberal.com", "https://www.mymcr.net/news/", "https://www.morgancountycitizen.com", "https://www.columbusga.gov/News", "https://www.co.newton.ga.us/156/News", "https://www.oconeecounty.com/156/News", "https://www.theoglethorpeecho.com/local-news", "https://www.paulding.gov/156/News", "https://www.peachcountynews.com", "https://pickensprogress.com/", "https://www.blackshearnews.com", "https://pikecountygeorgia.com/", "https://www.polkcountyenterprise.com", "https://www.hawkinsvilleprogress.com", "https://www.eatontonmessenger.com", "https://www.thequitmanfreepress.com/", "https://www.theclaytontribune.com", "https://www.therandolphleader.com/news/", "https://www.augustaga.gov/156/News-Center", "https://www.rockdalecountyga.gov/156/News", "https://www.thesylvaniatimes.com/", "https://www.donalsonvillenews.com", "https://www.breckenridgetexan.com", "https://talbottonnewera.com/", "https://www.tattnalljournal.com", "https://www.taylorcountypress.com", "https://www.macontelegraph.com", "https://www.timesenterprise.com", "https://www.tiftongazette.com", "https://www.southeastsun.com", "https://www.northgeorgianews.com", "https://www.troupcountyga.gov/News", "https://www.ashburnwire.com", "https://www.northgeorgianews.com", "https://www.thomastontimes.com", "https://www.walkercountygov.com/news", "https://www.waltoncountyga.gov/156/News", "https://www.warecountygazette.com", "https://www.wjbf.com/news/warren-county/", "https://www.thesandersvillereport.com", "https://www.thepress-sentinel.com", "https://www.whitecountynews.net", "https://www.whitfieldcountyga.com/news", "https://www.wilcoxsun.com", "https://www.wilkinsoncounty.net/category/news/", "https://www.sylvesterlocal.com", "https://www.co.anderson.tx.us/news", "https://www.andrewscountynews.com", "https://www.angelinacounty.net/county-news/", "https://www.aransascountytx.gov/news", "https://www.archercountynews.com", "https://austincountynewsonline.com/", "https://www.muleshoejournal.com", "https://www.banderabulletin.com/", "https://www.co.bastrop.tx.us/news", "https://www.seymournews.com", "https://www.bellcountytx.com/news", "https://www.bexar.org/CivicAlerts.aspx", "https://www.hillcountrypassport.com/blanco/", "https://www.co.borden.tx.us/", "https://www.bosquecountypublishing.com", "https://www.bowiecountynow.com/", "https://www.brazoriacountytx.gov/news", "https://www.brazoscountytx.gov/156/News", "https://www.valdostadailytimes.com", "https://www.burlesoncountyledger.com", "https://www.burnetbulletin.com/", "http://www.mycaldwellcounty.com/news", "https://www.callahancountynews.com", "https://www.cameroncountytx.gov/news", "https://www.pittsburgnews.com", "https://www.casscountynow.com/", "https://www.castrocountynews.com", "https://www.thecherokeean.com/", "https://www.childressindex.com", "https://www.colemantoday.com/", "https://www.collincountytx.gov/news", "https://www.coloradocountycitizen.com/", "https://www.co.comal.tx.us/News.htm", "https://www.thecomanchechief.com/news/county_news/", "https://www.cranenews.com", "https://crockettcountytimes.com/", "https://www.crosbycountynews.com", "https://www.dallamcountynews.com", "https://www.dallascounty.org/news", "https://www.lamesacourier.com", "https://www.deltacountyindependent.com/", "https://www.dentoncounty.gov/156/News", "https://www.cuerorecord.com", "https://www.carrizoenterprise.com", "https://www.clarendonlive.com", "https://www.duvalcountytimes.com", "https://www.co.ellis.tx.us/156/News", "https://www.epcounty.com/news.htm", "https://www.marlinnews.com", "https://www.fannin.news", "https://www.fayettecountyrecord.com/", "https://www.floydadanews.com", "https://www.fortbendcountytx.gov/news", "https://www.mtvernonnews.com", "https://freestonecountytimesonline.com/", "https://www.friotime.com", "https://www.galvestontx.gov/156/Notify-Me", "https://www.postdispatch.com", "https://www.fredericksburgstandard.com", "https://www.gonzalesinquirer.com", "https://www.co.grayson.tx.us/news", "https://www.navasotanews.com", "https://www.co.guadalupe.tx.us/news", "https://www.hamiltonherald-news.com", "https://www.hansfordnews.com", "https://www.hardincoindependent.com/category/news/", "https://www.harriscountytx.gov/News", "https://www.haskellstar.com", "https://www.hayscountytx.gov/news"
]

# Custom user agents for evading detection
USER_AGENTS = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Mozilla/5.0 (iPhone; CPU iPhone OS 14_0 like Mac OS X) AppleWebKit/537.36 (KHTML, like Gecko) Version/14.0 Mobile/15E148 Safari/537.36"
]

async def scrape_news_urls():
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)

        all_news_urls = {}

        for site in NEWS_SITES:
            user_agent = random.choice(USER_AGENTS)

            # Set user agent when creating the context
            context = await browser.new_context(user_agent=user_agent)
            page = await context.new_page()

            try:
                print(f"Scraping: {site}")
                await page.goto(site, timeout=60000)
                await page.wait_for_load_state("domcontentloaded")

                # Extract links
                links = await page.eval_on_selector_all(
                    "a[href]", "elements => elements.map(el => el.href)"
                )

                # Filter only news article URLs (exclude irrelevant ones)
                article_urls = list(set(filter(lambda x: "fire" in x.lower(), links)))

                all_news_urls[site] = article_urls
                print(f"Found {len(article_urls)} articles from {site}")

            except Exception as e:
                print(f"Error scraping {site}: {e}")

            await page.close()
            await context.close()

        # Save results
        with open("fire_news_urls1.json", "w") as f:
            json.dump(all_news_urls, f, indent=4)

        await browser.close()
        print("Scraping completed. Data saved to fire_news_urls.json")

# Run the scraper
asyncio.run(scrape_news_urls())
