import json
import random
import asyncio
from playwright.async_api import async_playwright

# List of search pages for fire-related news
NEWS_SITES = [
    "https://www.cnn.com/search?q=fire",
    "https://www.foxnews.com/search-results/search?q=fire",
    "https://www.nbcnews.com/search/?q=fire",
    "https://www.cbsnews.com/search/?q=fire",
    "https://www.abcnews.go.com/search?q=fire",
    "https://www.nytimes.com/search?query=fire",
    "https://www.latimes.com/search?q=fire",
    "https://www.chicagotribune.com/search/?q=fire",
    "https://www.boston.com/search/?q=fire",
    "https://www.dallasnews.com/search/?q=fire",
    "https://local12.com/search?find=fire",
    "https://www.wtnh.com/?submit&s=fire&orderby=modified",
   "https://www.wtnh.com/page/2/?submit&s=fire&orderby=modified",
   "https://www.wtnh.com/page/3/?submit&s=fire&orderby=modified",
    "https://www.cbs17.com/?submit=&s=fire&orderby=modified",
    "https://www.cbs17.com/page/2/?submit&s=fire&orderby=modified",
    "https://www.cbs17.com/page/3/?submit&s=fire&orderby=modified",
    "https://www.wbir.com/search?q=fire",
    "https://www.wcvb.com/search?q=fire",
    "https://www.knoxnews.com/search/?q=fire",
    "https://westchester.news12.com/search?q=fire",
    "https://www.wfmz.com/search/?q=fire",
    "https://news4sanantonio.com/search?find=fire",
    "https://www.wivb.com/?submit=&s=fire",
    "https://www.nbcconnecticut.com/?s=fire",
    "https://www.al.com/search/?q=fire",
    "https://cullmantimes.com/",
        "https://www.westvalleyview.com/search/?q=fire",
    "https://www.chandlernews.com/search/?q=fire",
    "https://www.glendalestar.com/search/?q=fire",
    "https://www.yourvalley.net/search/?q=fire",
    "https://www.gilbertsunnews.com/search/?q=fire",
    "https://flagscanner.com/?s=fire",
    "https://www.yumanewsnow.com/search/?q=fire",
    "https://www.havasunews.com/search/?q=fire",
    "https://www.tucsonsentinel.com/search/?q=fire",
    "https://www.tucsonlocalmedia.com/search/?q=fire",
    "https://www.gvnews.com/search/?q=fire",
        "https://www.kodiakdailymirror.com/search/?q=fire",
    "https://sitkasentinel.com/search/?q=fire",
    "https://www.latimes.com/search?q=fire",
    "https://www.dailynews.com/search/?q=fire",
    "https://www.laweekly.com/search/?q=fire",
    "https://www.ladowntownnews.com/search/?q=fire",
    "https://www.glendalenewspress.com/search/?q=fire",
    "https://www.burbankleader.com/search/?q=fire",
    "https://www.pasadenastarnews.com/search/?q=fire",
    "https://www.dailybreeze.com/?s=fire&orderby=date&order=desc",
    "https://malibutimes.com/?s=fire",
    "https://smdp.com/?s=fire",
    "https://www.fresnostatenews.com//?s=fire",
    "https://www.selmaenterprise.com",
    "https://kerwestnewspapers.com",
    "https://www.sfchronicle.com",
    "https://www.sfexaminer.com",
    "https://www.sanfranciscochinatown.com",
    "https://sfbayview.com",
    "https://www.sacramentopress.com",
    "https://elkgrovetribune.com",
    "https://goldcountrymedia.com",
    "https://citrusheightssentinel.com",
    "https://www.davisenterprise.com",
    "https://www.natomasbuzz.com",
    "https://www.carmichaeltimes.com",
    "https://sacramento.newsreview.com",
    "https://www.mercurynews.com",
    "https://sanjosespotlight.com",
    "https://local.newsbreak.com",
    "https://www.bakersfield.com",
    "https://www.anaheim.net",
    "https://www.independent.com",
    "https://www.santamariasun.com",
    "https://goletavoice.com",
    "https://santamariatimes.com",
    "https://lompocrecord.com",
    "https://syvnews.com",
    "https://www.montecitojournal.net",
    "https://dailynexus.com",
    "https://www.longbeachlocalnews.com",
    "https://www.sandiegouniontribune.com",
    "https://timesofsandiego.com",
    "https://www.chulavistatoday.com",
    "https://www.times-advocate.com",
    "https://thecoastnews.com",
    "https://www.thevistapress.com",
    "https://www.sanmarcosrecord.com",
    "https://www.imperialbeachnewsca.com",
    "https://signalscv.com",
    "https://www.dailycommerce.news",
    "https://www.thecamarilloacorn.com",
    "https://www.newsbreak.com",
    "https://vidanewspaper.com",
    "https://www.vcstar.com",
    "https://www.toacorn.com",
    "https://www.simivalleyacorn.com",
    "https://www.fillmoregazette.com",
    "https://www.mpacorn.com",
    "https://www.ojaivalleynews.com",
    "https://santapaulatimes.com",
    "https://www.desertsun.com",
    "https://orangecountytribune.com",
    "https://www.aspendailynews.com/",
    "https://www.dailycamera.com/",
    "https://www.canoncitydailyrecord.com/",
    "https://gazette.com/",
    "https://www.craigdailypress.com/",
    "https://www.durangoherald.com/",
    "https://www.coloradoan.com/",
    "https://www.fortmorgantimes.com/",
    "https://www.summitdaily.com/",
    "https://www.gjsentinel.com/",
    "https://www.greeleytribune.com/",
    "https://www.lajuntatribunedemocrat.com/",
    "https://www.timescall.com/",
    "https://www.reporterherald.com/",
    "https://www.montrosepress.com/",
    "https://www.chieftain.com/",
    "https://www.vaildaily.com/",
    "https://www.ctpost.com/",
    "https://www.bristolpress.com/",
    "https://www.greenwichtime.com/",
    "https://www.newstimes.com/",
    "https://www.courant.com/",
    "https://www.ctinsider.com",
    "https://www.middletownpress.com/",
    "https://www.nhregister.com/",
    "https://theday.com/",
    "https://www.thehour.com/",
    "https://www.norwichbulletin.com/",
    "https://www.stamfordadvocate.com/",
    "https://www.rep-am.com/",
    "https://www.thechronicle.com/",
    "https://baytobaynews.com/",
    "https://www.delawareonline.com/",
    "https://washingtoncitypaper.com",
    "https://www.washingtonpost.com",
    "https://www.washingtonian.com",
    "https://www.heraldtribune.com",
    "https://www.snntv.com",
    "https://www.mysuncoast.com",
    "https://thebradentontimes.com",
    "https://www.bradenton.com",
    "https://cityofbradenton.com",
    "https://www.tampabay.com",
    "https://www.wtsp.com",
    "https://www.tampabeacon.com",
    "https://fortmyers.floridaweekly.com",
    "https://www.miaminewtimes.com",
    "https://www.miamiherald.com",
    "https://www.miamitodaynews.com",
    "https://www.orlandoweekly.com",
    "https://www.cityofcocoabeach.com",
    "https://www.ocala.com",
    "https://www.ocalagazette.com",
    "https://www.jaxdailyrecord.com",
    "https://www.yoursun.com",
    "https://veronews.com",
    "https://www.tcpalm.com",
    "https://www.cityofpsl.com",
    "https://ourtallahassee.com",
    "https://www.news-press.com",
    "https://www.hollywoodreporter.com",
    "https://www.gainesville.com",
    "https://palmbaylive.com",
    "https://www.palmbeachpost.com",
    "https://lakelandtimes.com",
    "https://communitynewspapers.com",
    "https://thegavoice.com",
    "https://www.mdjonline.com",
    "https://patch.com",
    "https://decaturish.com",
    "https://www.augustachronicle.com",
    "https://maconhomepress.com",
    "https://www.savannahtribune.com",
    "https://www.onlineathens.com",
    "https://www.rdrnews.com",
    "https://www.hawaiitribune-herald.com/",
    "https://www.staradvertiser.com/",
    "https://www.westhawaiitoday.com/",
    "https://www.thegardenisland.com/",
    "https://www.mauinews.com/",
    "https://cdapress.com/",
    "https://www.postregister.com/",
    "https://www.lmtribune.com/",
    "https://www.idahopress.com/",
    "https://www.idahostatejournal.com/",
    "https://shoshonenewspress.com/",
    "https://magicvalley.com",
    "https://www.news-gazette.com",
    "https://capitolnewsillinois.com",
    "https://www.chicagotribune.com",
    "https://www.thewoodstockindependent.com",
    "https://www.dailyherald.com",
    "https://www.positivelynaperville.com",
    "https://www.vevaynewspapers.com",
    "https://www.madisoncourier.com",
    "https://www.indystar.com",
    "https://www.ibj.com",
    "https://apnews.com",
    "https://www.tristatehomepage.com",
    "https://www.courierpress.com",
    "https://www.greaterfortwayneinc.com",
    "https://bloomingtonian.com",
    "https://ground.news",
    "https://www.kokomotribune.com",
    "https://www.tribstar.com",
    "https://andersonian.com",
    "https://www.amestrib.com/",
    "https://www.swiowanewssource.com/",
    "https://www.mississippivalleypublishing.com/the_hawk_eye/",
    "https://carrollspaper.com/",
    "https://www.thegazette.com/",
    "https://www.ottumwacourier.com/",
    "https://www.charlescitypress.com/",
    "https://www.chronicletimes.com/",
    "https://www.clintonherald.com/",
    "https://spectrumnews1.com",
    "https://www.courier-journal.com",
    "https://www.pmg-ky1.com",
    "https://www.wave3.com",
    "https://bgdailynews.com",
    "https://www.richmondregister.com",
    "https://linknky.com",
    "https://www.dailyindependent.com/",
    "https://bgdailynews.com/",
    "https://www.thetimestribune.com/",
    "https://www.amnews.com/",
    "https://www.thenewsenterprise.com/",
    "https://www.state-journal.com/",
    "https://www.harlanenterprise.net/",
    "https://www.thegleaner.com/",
    "https://www.kentuckynewera.com/",
    "https://www.middlesboronews.com/",
    "https://www.the-messenger.com/",
    "https://www.theadvocate.com",
    "https://www.brproud.com",
    "https://theneworleanstribune.com",
    "https://www.gretnaguide.com",
    "https://www.thestbernardvoice.com",
    "https://covingtonweekly.com",
    "https://www.hammondstar.com",
    "https://www.plaqueminesgazette.com",
    "https://www.kenner.la.us",
    "https://thedailyiberian.com",
    "https://www.centralmaine.com/",
    "https://www.bangordailynews.com/",
    "https://www.pressherald.com/times-record/",
    "https://www.sunjournal.com/",
    "https://www.baltimoresun.com",
    "https://baltimoretimes-online.com",
    "https://www.thebaltimorebanner.com",
    "https://gaithersburgpost.town.news",
    "https://www.marylandmatters.org",
    "https://www.middletownpress.com/",
    "https://www.thecitizen.com/",
    "https://www.delmarvanow.com/",
    "https://www.dailypress.com",
    "https://www.dailypress.com/",
    "https://www.fairfaxtimes.com",
    "https://www.clarionledger.com",
    "https://www.magnoliareporter.com",
    "https://www.nwahomepage.com",
    "https://www.nwnews.com",
    "https://www.pennlive.com",
    "https://www.thedailyreview.com",
    "https://www.delcotimes.com",
    "https://www.spotlightpa.org",
    "https://www.nj.com",
    "https://www.newjerseyherald.com",
    "https://www.pressofatlanticcity.com"
]

# Custom user agents for evading detection
USER_AGENTS = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Mozilla/5.0 (iPhone; CPU iPhone OS 14_0 like Mac OS X) AppleWebKit/537.36 (KHTML, like Gecko) Version/14.0 Mobile/15E148 Safari/537.36"
]

async def scrape_news_urls():
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)

        all_news_urls = {}

        for site in NEWS_SITES:
            user_agent = random.choice(USER_AGENTS)

            # Set user agent when creating the context
            context = await browser.new_context(user_agent=user_agent)
            page = await context.new_page()

            try:
                print(f"Scraping: {site}")
                await page.goto(site, timeout=60000)
                await page.wait_for_load_state("domcontentloaded")

                # Extract links
                links = await page.eval_on_selector_all(
                    "a[href]", "elements => elements.map(el => el.href)"
                )

                # Filter only news article URLs (exclude irrelevant ones)
                article_urls = list(set(filter(lambda x: "fire" in x.lower(), links)))

                all_news_urls[site] = article_urls
                print(f"Found {len(article_urls)} articles from {site}")

            except Exception as e:
                print(f"Error scraping {site}: {e}")

            await page.close()
            await context.close()

        # Save results
        with open("fire_news_urls.json", "w") as f:
            json.dump(all_news_urls, f, indent=4)

        await browser.close()
        print("Scraping completed. Data saved to fire_news_urls.json")

# Run the scraper
asyncio.run(scrape_news_urls())
